name: Run tests on push
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Test with docker-compose
        run: >
          docker-compose -f ./scripts/test/docker/docker-compose.yml
          up
          --build
          --abort-on-container-exit
          --exit-code-from tags-drive
